#!/stand/sh
# -*- tab-width:  4 ;; Emacs
# vi: set tabstop=4 :: Vi/ViM

# If running as xarchInstall, only use binaries in `/stand'
[ "$xarchInstall" ] && export PATH=/stand
############################################################ CONFIGURATION

# Whether to use ANSI color or not
ANSI_COLOR=YES

dir=/dist/run_once

############################################################ FUNCTIONS

# Include standard functions
. /dist/druid/etc/sh.subr

############################################################ MAIN SOURCE

#
# Recursively search the `run_once' directory, executing any/all shell-scripts
# that are (a) executable and (b) named `*.sh'.
#
find $dir -type f -name '*.sh' -perm +0111 -exec sh '{}' ';'

# Introduce a delay if configured
[ "$HUMAN_DELAY" ] && sleep $HUMAN_DELAY

################################################################################
# END
################################################################################
#
# $Header: /cvsroot/druidbsd/druidbsd/druid83/dep/freebsd/druid/run_once,v 1.1 2012/10/10 23:29:56 devinteske Exp $
#
# $Copyright: 2006-2012 Devin Teske. All rights reserved. $
#
# $Log: run_once,v $
# Revision 1.1  2012/10/10 23:29:56  devinteske
# Commit initial public beta release of 8.3 series (beta 57; on-par with
# the 9.0 series released recently, also beta 57).
#
#
################################################################################
