#!/stand/sh
# -*- tab-width:  4 ;; Emacs
# vi: set tabstop=4 :: Vi/ViM

# If running as xarchInstall, only use binaries in `/stand'
[ "$xarchInstall" ] && export PATH=/stand
############################################################ CONFIGURATION

# Indicate that we want color output
ANSI_COLOR=YES

dir=/dist/sys_custom

############################################################ FUNCTIONS

# Include standard functions
. /dist/druid/etc/sh.subr

############################################################ MAIN SOURCE

print_bold "Copying \`%s' to the root filesystem... " "$dir"
printf "(this may take some time)\n"
sleep 3

copy_directory -s "$dir/" "/"
print_green "Successfully copied \`%s'!" "$dir"
sleep 1; echo

[ "$HUMAN_DELAY" ] && sleep $HUMAN_DELAY

################################################################################
# END
################################################################################
#
# $Header: /cvsroot/druidbsd/druidbsd/druid83/dep/freebsd/druid/syscustom,v 1.1 2012/10/10 23:29:56 devinteske Exp $
#
# $Copyright: 2006-2012 Devin Teske. All rights reserved. $
#
# $Log: syscustom,v $
# Revision 1.1  2012/10/10 23:29:56  devinteske
# Commit initial public beta release of 8.3 series (beta 57; on-par with
# the 9.0 series released recently, also beta 57).
#
#
################################################################################
