#!/bin/sh
# -*- tab-width:  4 -*- ;; Emacs
# vi: set tabstop=4     :: Vi/ViM
############################################################ CONFIGURATION

# Whether to use ANSI color or not
export ANSI_COLOR=YES

# Execution root (within the memory file-system)
export CMD_ROOT=/fis

# Local mount point to use when mounting the boot media
export cd_mount_point=/cdrom

# Internal ISO9660 Volume ID/Label of our boot device
# NOTE: This is a hard-coded value in the ISO9660 compilation process.
#
export VOLID=druid

############################################################ FUNCTIONS

# Include standard functions
. "$CMD_ROOT/sh.subr"

############################################################ MAIN SOURCE

#
# Perform initialization routines
#
task_begin "Verifying installation environment sanity..."
trunc_safe "$CMD_ROOT/menu-install.cfg"
die_if_missing "/bin/sleep"
die_if_missing "/sbin/mount_cd9660"
die_if_missing "/tmp"
task_end $SUCCESS

#
# Mount the media that we booted from
#
task_begin "Mounting ISO9660 filesystem on \`$cd_mount_point'..."
if [ ! -f "$cd_mount_point/version.inf" ]; then

	# Attempt to mount /dev/iso9660/VOLID
	eval_spin mount_cd9660 "/dev/iso9660/$VOLID" "$cd_mount_point"

	if [ $? -eq $SUCCESS ]; then
		# Make sure we've mounted something we built/recognize
		[ -f "$cd_mount_point/version.inf" ] \
			|| die "$FATAL_ERROR Invalid installation source"
	else
		die "$UNKNOWN_ERROR Could not mount ISO9660 filesystem"
	fi
fi
task_end $SUCCESS

#
# Start an instance of the custom install menu
#
print_bold "Launching installation menu..."
sleep 1.5
menu="$cd_mount_point/freebsd/menu/menu"
[ -f "$menu" ] \
	|| menu="$cd_mount_point/menu/menu"
die_if_missing "$menu"
export MENU_ROOT="${menu%/*}"
( cd "$MENU_ROOT" && "./${menu##*/}" ) || exit $FAILURE

exit $SUCCESS

################################################################################
# END
################################################################################
#
# $Header: /cvsroot/druidbsd/druidbsd/druid83/dep/freebsd/mfsroot/standard/src/fis/load_menu,v 1.1 2012/10/10 23:29:59 devinteske Exp $
#
# $Copyright: 2006-2012 Devin Teske. All rights reserved. $
#
################################################################################
